version: 2

updates:
    -   package-ecosystem: npm
        directory: "/"
        schedule:
            interval: "weekly"
        target-branch: "develop"

    -   package-ecosystem: composer
        directory: "/"
        schedule:
            interval: "weekly"
        target-branch: "develop"
